USE_GT = False
SCANREFER_ENHANCE = False
SCANREFER_ENHANCE_VANILLE = False
SCANREFER_ENHANCE_LOSS_THRESHOLD = 0.5
SCANREFER_ENHANCE_EVAL_THRESHOLD = 0.1
EVAL_SAVE_NAME = f"vanilla_0.5_pred_thre_{SCANREFER_ENHANCE_EVAL_THRESHOLD}"