USE_GT = False
SCANREFER_ENHANCE = True
SCANREFER_ENHANCE_VANILLE = True
SCANREFER_ENHANCE_LOSS_THRESHOLD = 0.5
SCANREFER_ENHANCE_EVAL_THRESHOLD = 0.4
EVAL_SAVE_NAME = f"vanilla_0.5_pred_thre_{SCANREFER_ENHANCE_EVAL_THRESHOLD}"